apiVersion: v1
kind: Service
metadata:
  name: {{ include "nfs-server-alpine.fullname" . }}
  labels:
    {{- include "nfs-server-alpine.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: nfs
      port: 2049
    - name: mountd
      port: 20048
    - name: rpcbind
      port: 111
  selector:
    {{- include "nfs-server-alpine.selectorLabels" . | nindent 4 }}
