name: lint

on:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup helm
        uses: azure/setup-helm@v1

      - run: helm lint chart/*
